DROP INDEX PK_MEMBER;

/* 회원 */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 회원 */
CREATE TABLE MEMBER (
	USER_ID VARCHAR2(20) NOT NULL, /* 회원_ID */
	PASSWD VARCHAR2(20) NOT NULL, /* 비밀번호 */
	NAME VARCHAR2(30) NOT NULL, /* 이름 */
	EMAIL VARCHAR2(320) NOT NULL, /* 이메일 */
	BIRTH CHAR(8), /* 생일 */
	CELLPHONE VARCHAR2(20) NOT NULL, /* 핸드폰 */
	RANKING VARCHAR2(2) DEFAULT '1', /* 등급 */
	REG_DT DATE DEFAULT SYSDATE, /* 등록일 */
	REG_ID VARCHAR2(20), /* 등록자 */
	MOD_DT DATE DEFAULT SYSDATE, /* 수정일 */
	MOD_ID VARCHAR2(20) /* 수정자 */
);

COMMENT ON TABLE MEMBER IS '회원';

COMMENT ON COLUMN MEMBER.USER_ID IS '회원_ID';

COMMENT ON COLUMN MEMBER.PASSWD IS '비밀번호';

COMMENT ON COLUMN MEMBER.NAME IS '이름';

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.BIRTH IS '생일';

COMMENT ON COLUMN MEMBER.CELLPHONE IS '핸드폰';

COMMENT ON COLUMN MEMBER.RANKING IS '등급';

COMMENT ON COLUMN MEMBER.REG_DT IS '등록일';

COMMENT ON COLUMN MEMBER.REG_ID IS '등록자';

COMMENT ON COLUMN MEMBER.MOD_DT IS '수정일';

COMMENT ON COLUMN MEMBER.MOD_ID IS '수정자';

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		USER_ID ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			USER_ID
		);