--CATS로 DEPT_TCL생성
CREATE TABLE DEPT_TCL
AS
SELECT * FROM dept;

--DEPT_TCL DML작업
--INSERT
INSERT INTO DEPT_TCL VALUES(50,'DATABASE','SEOUL');
--UPDATE
UPDATE DEPT_TCL SET LOC = 'BUSAN'
WHERE deptno = 40;
--DELETE
DELETE FROM DEPT_TCL 
WHERE DNAME = 'RESEARCH';
--SELECT확인
SELECT * FROM DEPT_TCL;
--ROLLBACK : DML작업들이 취소 되었는지 확인
--트랜잭션을 취소
ROLLBACK;