--DEPT_TCL DML작업
--INSERT
INSERT INTO DEPT_TCL VALUES(50,'DATABASE','SEOUL');
--UPDATE
UPDATE DEPT_TCL SET LOC = 'BUSAN'
WHERE deptno = 40;
--DELETE
DELETE FROM DEPT_TCL 
WHERE DNAME = 'RESEARCH';
--SELECT확인
SELECT * FROM DEPT_TCL;
--COMMIT : 트랜잭션을 영구 반영 되었는지 확인
--트랜잭션을 영구 반영
--ROLLBACK 해도 다시 돌아가지 않음
COMMIT;