SELECT t1.owner,
       t1.constraint_name,
       t1.constraint_type,
       t1.table_name
FROM user_constraints t1
WHERE t1.table_name IN( 'TABLE_UNIQUE2');

--RENAME
ALTER TABLE TABLE_UNIQUE2
RENAME CONSTRAINT TBLUNQ02_TEL_UNQ TO TBLUNQ02_TEL_UNQ99;


--MODIFY : DROP,MODIFY
ALTER TABLE TABLE_UNIQUE2
DROP CONSTRAINT TBLUNQ02_TEL_UNQ99;

ALTER TABLE TABLE_UNIQUE2
MODIFY(TEL CONSTRAINT TBLUNQ02_TEL_UNQ99 UNIQUE);