--1. DEPT_TRG 테이블 만들기
CREATE TABLE DEPT_TRG
AS
SELECT * FROM DEPT_TRG;

SELECT * FROM DEPT_TRG;

--2. DEPT_TRG_LOG테이블 만들기
CREATE TABLE DEPT_TRG_LOG
(
    TABLENAME   VARCHAR2(10),
    DML_TYPE    VARCHAR2(10),
    DEPTNO      NUMBER(2),
    USER_NAME   VARCHAR2(30),
    CHANGE_DATE DATE
);

SELECT * FROM DEPT_TRG_LOG;

--3.트리거 DEPT_TRG테이블에 TRG_DEPT_LOG 작성
CREATE OR REPLACE TRIGGER TRG_DEPT_LOG
AFTER
INSERT OR UPDATE OR DELETE ON DEPT_TRG
FOR EACH ROW

BEGIN
    IF INSERTING THEN
        INSERT INTO DEPT_TRG_LOG
        VALUES('DEPT_TRG','INSERT',:NEW.deptno,
                SYS_CONTEXT('USERENV','SESSION_USER'),SYSDATE);
     ELSIF UPDATING THEN
        INSERT INTO DEPT_TRG_LOG
        VALUES('DEPT_TRG','UPDATE',:OLD.deptno,
                SYS_CONTEXT('USERENV','SESSION_USER'),SYSDATE);
     ELSIF DELETING THEN
        INSERT INTO DEPT_TRG_LOG
        VALUES('DEPT_TRG','DELETR',:OLD.deptno,
                 SYS_CONTEXT('USERENV','SESSION_USER'),SYSDATE);
    END IF;
END;
/

INSERT INTO DEPT_TRG VALUES(99,'TEST_DNAME','SEOUL');

UPDATE DEPT_TRG 
    SET LOC = 'TEST_LOC'
WHERE DEPTNO = 99;

DELETE FROM DEPT_TRG
WHERE DEPTNO = 99;

SELECT * FROM DEPT_TRG;

SELECT * FROM DEPT_TRG_LOG;