CREATE SEQUENCE T_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 10
NOCYCLE
;
--Sequence T_SEQ이(가) 생성되었습니다.

CREATE TABLE T_SEQ_TEST
(
    NO NUMBER DEFAULT T_SEQ.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(10)
);
--Table T_SEQ_TEST이(가) 생성되었습니다.