CREATE TABLE CHAP10HW_EMP      AS SELECT * FROM emp;
CREATE TABLE CHAP10HW_DEPT     AS SELECT * FROM dept;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM salgrade;

SELECT *
FROM CHAP10HW_DEPT;

INSERT INTO CHAP10HW_DEPT
VALUES (50,'ORACLE','BUSAN');
INSERT INTO CHAP10HW_DEPT
VALUES (60,'SQL','ILSAN');
INSERT INTO CHAP10HW_DEPT
VALUES (70,'SELECT','INCHEON');
INSERT INTO CHAP10HW_DEPT
VALUES (80,'DML','BUNDANG');

SELECT * FROM CHAP10HW_DEPT;